# Generated by Django 5.2.3 on 2025-07-01 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdzunaJobs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_import', models.DateTimeField()),
                ('description', models.TextField()),
                ('entreprise', models.CharField(max_length=255)),
                ('intitule', models.CharField(max_length=255)),
                ('lieu', models.CharField(max_length=255)),
                ('secteur', models.CharField(max_length=255)),
                ('skills', models.TextField()),
            ],
            options={
                'db_table': 'adzuna_jobs',
            },
        ),
        migrations.CreateModel(
            name='BaseDeDonnees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('base_de_donnee', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'base_de_donnees',
            },
        ),
        migrations.CreateModel(
            name='FrameworkWeb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('framework', models.CharField(max_length=100)),
                ('langage', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'framework_web',
            },
        ),
        migrations.CreateModel(
            name='Plateformes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plateforme', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'plateformes',
            },
        ),
        migrations.CreateModel(
            name='TopTechnosVoulues',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nb_offres', models.IntegerField()),
                ('techno', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'top_technos_voulues',
            },
        ),
        migrations.CreateModel(
            name='UserAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=40, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
