# Generated by Django 5.2.3 on 2025-07-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChallengeDataLakeAPI', '0002_adzunajob_database_platform_webframework_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRepo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=100)),
                ('stargazers_count', models.IntegerField()),
                ('forks_count', models.IntegerField()),
                ('html_url', models.CharField(max_length=500)),
                ('open_issues_count', models.IntegerField()),
                ('watchers_count', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('license', models.CharField(max_length=255)),
                ('homepage', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'github_repo',
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=100)),
                ('contract', models.CharField(max_length=100)),
                ('remote', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'job_offer',
            },
        ),
        migrations.CreateModel(
            name='RemotekoJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('job_link', models.TextField()),
            ],
            options={
                'db_table': 'remoteko_job',
            },
        ),
    ]
