# Generated by Django 5.2.3 on 2025-07-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChallengeDataLakeAPI', '0003_githubrepo_joboffer_remotekojob'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RemotekoJob',
            new_name='RemoteokJob',
        ),
        migrations.AlterModelTable(
            name='remoteokjob',
            table='remoteok_job',
        ),
    ]
